### ISSUE TITLE
@ character error

### ISSUE THREAD

**Issue by Grypss** [andrewjsi/amisms#1]
Dear Andrewjsi!

I send sms whitch contain "@" character. The sms has arrived, but seen "@" character instead of "i" character.

Thanks, Gryps

**Comment by andrewjsi** [comment]
Dear Gryps!

Do you checked out the latest revision of master branch?

regards,
Andras

**Comment by andrewjsi** [comment]
Please pull your amisms, compile and try again! Was temporary fixed the @ character, but the problem is with the whole character encoding in the amisms PDU converter..

**Comment by Grypss** [comment]
Dear Andras!

It works perfectly well! Thanks!

Regards,
Gryps
